application:
  max-allowed-books: 3

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 2022
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl